### PR TITLE
update view on mode change

### PR DESCRIPTION
**Pull request by falk-werner**
Get rid of unnecessary view updates. View is updated, when mode is switches from edit mode to view mode.

### CODE REVIEW

**Comment by falk-werner** [comment]
This pull request minimizes unnecessary view updates only. There are also unnecessary calls to "save". I'm not sure if this should also be fixed with this pull request (maybe an separate one is more sufficient?). To get rid of unnecessary "save" requests, a dirty flag should be introduced, but I'm not quite sure where to put this:

The easiest way is to put it into the NoteFrame widget. But I don't want to add too much logic to the widgets, since they are not really testable... _(well there aren't much tests yet)_.

A better solution is to put the dirty flag into the Note class (modell). This solution will be testable but it comes with some rework.

There are 3 different options here:
- forget about the dirty flag now and solve the unnecessary view update only
- add the dirty flag to NoteFrame widget
-  add the dirty flag to Note class and rework some code

Any perferences or suggestions?

**Comment by hmlampe** [comment]
what for is the dirty flag needed? every time we leave the edit view, we save, in addition with ctrl+s, that should be enough

**Comment by falk-werner** [comment]
> what for is the dirty flag needed? every time we leave the edit view, we save, in addition with ctrl+s, that should be enough

It is not really needed but it helps to prevent unnecessary save operations. We mark a note as "dirty" whenever its name or contents are changed. We reset the dirty flag whenever a note is saved. When a note is saved but the dirty flag is not set, we don't do anything.

Note that other solutions, e.g. [Notable](https://notable.app/) allow to sort notes by title, creation time or time of last modification. Each save operation on the file will update the modification time stamp. We do not have this feature yet and I'm not sure whether we should implement it, but a user might not be aware that switching between tabs is recognized as modification.

At least I think we should skip this feature for now ;-)

**Comment by hmlampe** [comment]
I think so, too. For that feature it is needed for sure, but the change can also be part of that feature.

**Review by hmlampe — APPROVED** [review]

**Pull request merged**
