### PR TITLE
Class diagram

### PR DESCRIPTION
**Pull request by hmlampe**
two class diagrams generated with pyreverse from pylint to keep an overview

### CODE REVIEW

**Comment by falk-werner** [comment]
The class diagram is very detailed... is there a way to automate this?

**Comment by falk-werner** [comment]
I think, we can skip the .dot file since pyreverse can generate it directly using `-o png`.
@hmlampe: would you please add a script to update the generated class diagram, e.g. `create_docs.sh` in the `doc` directory?

**Comment by falk-werner** [comment]
I've created a pull request containing the requested changes based on you pull request: [Class diagram #6](https://github.com/falk-werner/note.py/pull/6) 

Please tell me, if that is okay with you.

**Comment by hmlampe** [comment]
Yes, your proposal looks fine. The png is enough.

**Pull request merged**
