### PR TITLE
Styling

### PR DESCRIPTION
**Pull request by hmlampe**
this adds a styling in green for ttk from [forest-theme](https://github.com/rdbende/Forest-ttk-theme)
the standard styling is not really modern nor beautiful
to use this theme, a lot of pngs have to be added, i don't know if this is okay
an other option would be, to use 'clam', which is a standard theme for ttk, this was tried in the first commit

### CODE REVIEW

**Comment by falk-werner** [comment]
Well, I fear this pull request may break one of our top claims (see [README.md](https://github.com/falk-werner/note.py/blob/main/README.md)):
> [note.py](https://github.com/falk-werner/note.py) is yet another note taking app. It is aimed to be minimalistic and **is shipped as a single python file**.

I understand that we should aim to look out app a little nicer, but I would prefer a single python script shipped to the user... let me think about this.

**Comment by hmlampe** [comment]
Maybe this one is an option [style](https://github.com/rdbende/Sun-Valley-ttk-theme) as it would integrate its style as a requirement via pip

**Comment by falk-werner** [comment]
@hmlampe: Please look at [PR #17](https://github.com/falk-werner/note.py/pull/17) for an alternative solution that is less intrusive.

**Comment by falk-werner** [comment]
@hmlampe: Since we've merged [PR #17](https://github.com/falk-werner/note.py/pull/17) can we close this one?

**Pull request closed without merging**
